In [3]:
import sys

In [4]:
!{sys.executable} -m pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [5]:
import numpy as np
import math

In [6]:
def randomMatrix(y_size=10, x_size=10, range=100):
    return np.asmatrix(np.random.randint(range, size=(y_size, x_size)))


def orderedMatrix(y_size=10, x_size=10):
    return np.asmatrix(np.arange(x_size*y_size).reshape(y_size, x_size))


In [7]:
class ColIndex:
    def largestValue(matrix, verbose = False):
        if verbose:
            largestPosition  = np.argmax(matrix, axis=0)
            print("\nLargest value for verification of largest value")
            print("positions:") 
            print(largestPosition)
            print("values:")
            print(matrix[np.asarray(largestPosition),np.arange(matrix.shape[1])])
            
        return (np.argmax(matrix) % matrix.shape[1])

    def largestSum(matrix, verbose=False):
        if verbose:
            print("\n Cumulative totals for verification of largest sum")
            print(np.cumsum(matrix, axis=0))
        return np.argmax(np.sum(matrix, axis=0))
    
    def largestMedian(matrix, verbose=False):
        if verbose:
            centre_rows = [math.floor((matrix.shape[0]-1)/2),math.ceil((matrix.shape[0]-1)/2)]
            print("\n centre rows of sorted columns:")
            print(np.sort(matrix, axis=0)[centre_rows ])
            print("Column Median Values:")
            print(np.median(matrix, axis=0))
        return np.argmax(np.median(matrix, axis=0))


matrix = randomMatrix(10, 10)



In [8]:
print(matrix)
print("largest value col index: {0}".format(
    ColIndex.largestValue(matrix, verbose=True)))


[[ 9 91 58 21 25 34 33 30 90 98]
 [62 89 78 25 97 89 24 47 54 69]
 [ 9 71 45 27  4 58 53 11 79 15]
 [61 50 94 33 95  2 49 53 29 73]
 [65 55 47 98 47 28 28 67 58 99]
 [51 73 45 63 21 36 42 29 77 61]
 [82 20 95 45 59 54 81 42 90 45]
 [86 20 75 89 51  6 24 40 22 43]
 [98 30 57 97 36 12 14 14 45 36]
 [75 73 28 77  6 68 15 18 14 21]]

Largest value for verification of largest value
positions:
[[8 0 6 4 1 1 6 4 0 4]]
values:
[[98 91 95 98 97 89 81 67 90 99]]
largest value col index: 9


In [9]:
print(matrix)
print("largest sum col index: {0}".format(
    ColIndex.largestSum(matrix, verbose=True)))


[[ 9 91 58 21 25 34 33 30 90 98]
 [62 89 78 25 97 89 24 47 54 69]
 [ 9 71 45 27  4 58 53 11 79 15]
 [61 50 94 33 95  2 49 53 29 73]
 [65 55 47 98 47 28 28 67 58 99]
 [51 73 45 63 21 36 42 29 77 61]
 [82 20 95 45 59 54 81 42 90 45]
 [86 20 75 89 51  6 24 40 22 43]
 [98 30 57 97 36 12 14 14 45 36]
 [75 73 28 77  6 68 15 18 14 21]]

 Cumulative totals for verification of largest sum
[[  9  91  58  21  25  34  33  30  90  98]
 [ 71 180 136  46 122 123  57  77 144 167]
 [ 80 251 181  73 126 181 110  88 223 182]
 [141 301 275 106 221 183 159 141 252 255]
 [206 356 322 204 268 211 187 208 310 354]
 [257 429 367 267 289 247 229 237 387 415]
 [339 449 462 312 348 301 310 279 477 460]
 [425 469 537 401 399 307 334 319 499 503]
 [523 499 594 498 435 319 348 333 544 539]
 [598 572 622 575 441 387 363 351 558 560]]
largest sum col index: 2


In [10]:
print(matrix)
print("largest median col index: {0}".format(
    ColIndex.largestMedian(matrix, verbose=True)))


[[ 9 91 58 21 25 34 33 30 90 98]
 [62 89 78 25 97 89 24 47 54 69]
 [ 9 71 45 27  4 58 53 11 79 15]
 [61 50 94 33 95  2 49 53 29 73]
 [65 55 47 98 47 28 28 67 58 99]
 [51 73 45 63 21 36 42 29 77 61]
 [82 20 95 45 59 54 81 42 90 45]
 [86 20 75 89 51  6 24 40 22 43]
 [98 30 57 97 36 12 14 14 45 36]
 [75 73 28 77  6 68 15 18 14 21]]

 centre rows of sorted columns:
[[62 55 57 45 36 34 28 30 54 45]
 [65 71 58 63 47 36 33 40 58 61]]
Column Median Values:
[[63.5 63.  57.5 54.  41.5 35.  30.5 35.  56.  53. ]]
largest median col index: 0
